# Git aliases
# # Todos estos deberian ser seteados a traves de git config como en el siguiente ejemplo
# git config --global alias.co checkout
alias gs='git status'
alias ga='git add '
alias gcm='git commit -m '
alias gd='git diff'
alias gdc='git diff --cached'

# Instalacion rapida
alias sai='sudo apt install $1'

# Alias cortisimos para acciones muy habituales
alias e='$EDITOR '
alias gogo='xdg-open '
alias enw='emacs -nw '
