# Git aliases
alias gs='git status'
alias ga='git add '
alias gcm='git commit -m '
alias gd='git diff'
alias gdc='git diff --cached'

# Instalacion rapida
alias sai='sudo apt-get install '

# Usar pivotal-slacker facilmente
alias pt='pivotal-slacker '

# Alias cortisimos para acciones muy habituales
alias e='$EDITOR '
alias o='xdg-open '
